# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af98d98cbe93b8d11c477bc07ac2386115b7ef54e5dbe0382d31e4d9c9ac1766591182c6f4266ee9177fc5ebab336b49c1fe9993ac8e48850141d051164a145f

test:
  secret_key_base: 31bbfe683c829d0e4297c78e80cb092cc1bc5b6857b102e31547a5b282d7ce73da1dcc65708cc089743b89e0a9e252cd33c19663e0e596794c63073337ec6bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
